import { Scene01HeartBrain } from "./Scene01HeartBrain";
import { Scene02DecadesLater } from "./Scene02DecadesLater";
import { Scene03Cohort } from "./Scene03Cohort";
import { Scene04TwoGroups } from "./Scene04TwoGroups";
import { Scene05ScoredTested } from "./Scene05ScoredTested";
import { Scene06MoveSugar } from "./Scene06MoveSugar";
import { Scene07NotSame } from "./Scene07NotSame";
import { Scene08AnyMovement } from "./Scene08AnyMovement";
import { Scene09FastingGlucose } from "./Scene09FastingGlucose";
import { Scene10Threshold } from "./Scene10Threshold";
import { Scene11AlzheimerStake } from "./Scene11AlzheimerStake";
import { Scene12OneCity } from "./Scene12OneCity";
import { Scene13HeartBrainLink } from "./Scene13HeartBrainLink";
import { Scene14YearsLater } from "./Scene14YearsLater";

export const Scene01 = Scene01HeartBrain;
export const Scene02 = Scene02DecadesLater;
export const Scene03 = Scene03Cohort;
export const Scene04 = Scene04TwoGroups;
export const Scene05 = Scene05ScoredTested;
export const Scene06 = Scene06MoveSugar;
export const Scene07 = Scene07NotSame;
export const Scene08 = Scene08AnyMovement;
export const Scene09 = Scene09FastingGlucose;
export const Scene10 = Scene10Threshold;
export const Scene11 = Scene11AlzheimerStake;
export const Scene12 = Scene12OneCity;
export const Scene13 = Scene13HeartBrainLink;
export const Scene14 = Scene14YearsLater;
